FROM n8nio/runners:stable

USER root

COPY requirements.txt /opt/runners/task-runner-python/requirements.txt
RUN cd /opt/runners/task-runner-python && uv pip install -r requirements.txt

COPY n8n-task-runners.json /etc/n8n-task-runners.json

USER runner